### PR TITLE
#61 header bg refactored

### PR DESCRIPTION
**Pull request by Sky-De**
## Related Issue
refactor header background image inline style to use Tailwind classes #61

## Summary of Changes
i removed style and used img url for bg as tailwind calss
i couldn't install your project on my machine to run and check after refactore
but based on tailwind CSS DOCS it will work
https://tailwindcss.com/docs/background-image

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Thanks @Sky-De 

> i couldn't install your project on my machine to run

Could you share the issue you encountered trying to run the project?  Something I could help with?

> but based on tailwind CSS DOCS it will work
> https://tailwindcss.com/docs/background-image

Could it be those docs only apply to Tailwind v3?  We're using v2 and checking the deploy preview here in the PR, it looks like that background image is no longer appearing
https://deploy-preview-64--cheerful-melomakarona-41a6ad.netlify.app/
Screen Shot 2023-05-01 at 11 03 44 AM

If there is no compatible API for v2 let me know, I can look to upgrade the project to v3 if needed.  I see docs for background image in the v2 docs, but not this particular syntax?
https://v2.tailwindcss.com/docs/background-image

_**EDIT**_: just opened #66 and confirm your PR works as expected there.  Give me a little time to test and merge then I think this should indeed work as expected.  💯

**Comment by Sky-De** [comment]
I couldn't find anything in v2 docs
I will use class to fix it

**Comment by thescientist13** [comment]
Hey @Sky-De not sure if you saw my edit but I already have a PR up for Tailwind v3 and so your should work as is once I merge it in, so need to change anything here.  👍

(That said, I'm still curious to hear about what issue you had running the project locally, if you feel like sharing)

**Comment by Sky-De** [comment]
Ok
If it works
Merge it
Then i will be done
Otherwise let me know about it to fix it

**Review by thescientist13 — APPROVED** [review]
Thank you!

**Pull request merged**
