### PR TITLE
enhancement/issue 93 reuse header background image for footer

### PR DESCRIPTION
**Pull request by mughalfrazk**
## Related Issue
Issue is: https://github.com/AnalogStudiosRI/www.blissfestri.com/issues/93

## Summary of Changes
1. [x] Used transform to rotate and re-use the same tear-strip image used on the header for the footer.
1. [x] Fixed rotated text and icons too.

### CODE REVIEW

**Review by thescientist13 — COMMENTED** [review]
Nice, this looks good in the deploy preview!
Screen Shot 2023-06-04 at 1 30 59 PM

My only consideration around this approach of transforming the text back is if it would impact screen readers at all?  I did a Google search and found a couple references to this being the case like with `uppercase`
- https://benmyers.dev/blog/css-can-influence-screenreaders/
- https://www.stefanjudis.com/today-i-learned/text-transforms-affects-screen-readers-too/

Not sure if that would apply here, or as one of those articles pointed, maybe we just need to add an aria label?
> _Edited: As [Massimo Artizzu](https://twitter.com/MaxArt2501/status/1242129390693203970) pointed out, for the combination of Chrome and VoiceOver an additional aria-label fixes this screen reader behavior for uppercases characters._

FWIW I did a Lighthouse run against this preview deploy and it got a 💯 score for accessibility, so no major warning signs there at least.  Plus those articles are 2-3 years old now.

Thoughts @aholtzman ?

**Review by thescientist13 — APPROVED** [review]
I did find this [blog post](https://www.marcozehe.de/use-css3-transforms-makes-your-pages-more-accessible/) from a Mozilla engineer suggesting things like `rotate` wouldn't impact screen readers, so that seems very re-assuring for our use case!
> _he big advantage: Screen readers will still read the text OK because their reading order is not influenced by the visual appearance of the text. So even text rotated by 45 or 90 degrees will appear correctly in a screen reader’s virtual buffer._

**Review by thescientist13 — COMMENTED** [review]
Apologies for the merge conflicts here, just been working on some other needed features but I'll get these cleared up in a couple of days and then we can get this merged.  👍

**Review by thescientist13 — COMMENTED** [review]
Had a chance to catch up with @aholtzman on this one and he had another suggestion we should try instead of having to re-rotate the inner text.  Instead, we should just nest a `<div>` inside the `<footer>` and put the background image on that, and stack that on top of the text.

So roughly it would look like
```html
<footer>
  <div class="bg-[url('/assets/images/tear-strip.webp')] transform rotate-180 ...">
  </div>
  <div class="flex gap-x-4 justify-center mb-4">
    <!-- existing footer content goes here -->
  </div>
</footer>
```

Would like to give that a try if possible.  👍

**Comment by mughalfrazk** [comment]
> Had a chance to catch up with @aholtzman on this one and he had another suggestion we should try instead of having to re-rotate the inner text. Instead, we should just nest a `<div>` inside the `<footer>` and put the background image on that, and stack that on top of the text.
> 
> So roughly it would look like
> 
> ```
> <footer>
>   <div class="bg-[url('/assets/images/tear-strip.webp')] transform rotate-180 ...">
>   </div>
>   <div class="flex gap-x-4 justify-center mb-4">
>     
>   </div>
> </footer>
> ```
> 
> Would like to give that a try if possible. 👍

I can do that, no problem.

**Comment by mughalfrazk** [comment]
Text is not transformed now but still needed to add a wrapper <div> around text and icon to add background color and transformed image is used as a top border so no need to put the text on top of that.

**Review by thescientist13 — COMMENTED** [review]
Nice, thanks @mughalfrazk !  Let me work on the merge conflict then this should be good to go.  💯

**Pull request merged**
